// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $about from "./routes/about.tsx";
import * as $api_checkout from "./routes/api/checkout.ts";
import * as $api_contact from "./routes/api/contact.ts";
import * as $api_features from "./routes/api/features.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_packages from "./routes/api/packages.ts";
import * as $apply_id_ from "./routes/apply/[id].tsx";
import * as $blog from "./routes/blog.tsx";
import * as $careers from "./routes/careers.tsx";
import * as $case_studies_slug_ from "./routes/case-studies/[slug].tsx";
import * as $case_studies_index from "./routes/case-studies/index.tsx";
import * as $checkout from "./routes/checkout.tsx";
import * as $checkout_success from "./routes/checkout/success.tsx";
import * as $community from "./routes/community.tsx";
import * as $contact from "./routes/contact.tsx";
import * as $docs from "./routes/docs.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $help from "./routes/help.tsx";
import * as $index from "./routes/index.tsx";
import * as $learn_more_b2b_c2c_orchestration from "./routes/learn-more/b2b-c2c-orchestration.tsx";
import * as $learn_more_omnichannel_storefronts from "./routes/learn-more/omnichannel-storefronts.tsx";
import * as $learn_more_personalization from "./routes/learn-more/personalization.tsx";
import * as $learn_more_unified_commerce from "./routes/learn-more/unified-commerce.tsx";
import * as $legal_privacy from "./routes/legal/privacy.tsx";
import * as $legal_sla from "./routes/legal/sla.tsx";
import * as $legal_terms from "./routes/legal/terms.tsx";
import * as $partners from "./routes/partners.tsx";
import * as $partners_apply_tier_ from "./routes/partners/apply/[tier].tsx";
import * as $platform from "./routes/platform.tsx";
import * as $pricing from "./routes/pricing.tsx";
import * as $pricing_configurator from "./routes/pricing/configurator.tsx";
import * as $resources from "./routes/resources.tsx";
import * as $services from "./routes/services.tsx";
import * as $solutions from "./routes/solutions.tsx";
import * as $tutorials from "./routes/tutorials.tsx";
import * as $why_headless from "./routes/why-headless.tsx";
import * as $Configurator from "./islands/Configurator.tsx";
import * as $ContactForm from "./islands/ContactForm.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $FeatureTabs from "./islands/FeatureTabs.tsx";
import * as $Header from "./islands/Header.tsx";
import * as $InstallmentCalculator from "./islands/InstallmentCalculator.tsx";
import * as $MailSignupForm from "./islands/MailSignupForm.tsx";
import * as $RoiCalculator from "./islands/RoiCalculator.tsx";
import * as $StatCounter from "./islands/StatCounter.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/about.tsx": $about,
    "./routes/api/checkout.ts": $api_checkout,
    "./routes/api/contact.ts": $api_contact,
    "./routes/api/features.ts": $api_features,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/packages.ts": $api_packages,
    "./routes/apply/[id].tsx": $apply_id_,
    "./routes/blog.tsx": $blog,
    "./routes/careers.tsx": $careers,
    "./routes/case-studies/[slug].tsx": $case_studies_slug_,
    "./routes/case-studies/index.tsx": $case_studies_index,
    "./routes/checkout.tsx": $checkout,
    "./routes/checkout/success.tsx": $checkout_success,
    "./routes/community.tsx": $community,
    "./routes/contact.tsx": $contact,
    "./routes/docs.tsx": $docs,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/help.tsx": $help,
    "./routes/index.tsx": $index,
    "./routes/learn-more/b2b-c2c-orchestration.tsx":
      $learn_more_b2b_c2c_orchestration,
    "./routes/learn-more/omnichannel-storefronts.tsx":
      $learn_more_omnichannel_storefronts,
    "./routes/learn-more/personalization.tsx": $learn_more_personalization,
    "./routes/learn-more/unified-commerce.tsx": $learn_more_unified_commerce,
    "./routes/legal/privacy.tsx": $legal_privacy,
    "./routes/legal/sla.tsx": $legal_sla,
    "./routes/legal/terms.tsx": $legal_terms,
    "./routes/partners.tsx": $partners,
    "./routes/partners/apply/[tier].tsx": $partners_apply_tier_,
    "./routes/platform.tsx": $platform,
    "./routes/pricing.tsx": $pricing,
    "./routes/pricing/configurator.tsx": $pricing_configurator,
    "./routes/resources.tsx": $resources,
    "./routes/services.tsx": $services,
    "./routes/solutions.tsx": $solutions,
    "./routes/tutorials.tsx": $tutorials,
    "./routes/why-headless.tsx": $why_headless,
  },
  islands: {
    "./islands/Configurator.tsx": $Configurator,
    "./islands/ContactForm.tsx": $ContactForm,
    "./islands/Counter.tsx": $Counter,
    "./islands/FeatureTabs.tsx": $FeatureTabs,
    "./islands/Header.tsx": $Header,
    "./islands/InstallmentCalculator.tsx": $InstallmentCalculator,
    "./islands/MailSignupForm.tsx": $MailSignupForm,
    "./islands/RoiCalculator.tsx": $RoiCalculator,
    "./islands/StatCounter.tsx": $StatCounter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
